-- AlterTable
ALTER TABLE "PlatformSettings" ADD COLUMN     "afterSignInUrl" TEXT NOT NULL DEFAULT '/dashboard',
ADD COLUMN     "afterSignUpUrl" TEXT NOT NULL DEFAULT '/onboarding',
ADD COLUMN     "allowOAuthSignIn" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "analyticsRetentionDays" INTEGER NOT NULL DEFAULT 365,
ADD COLUMN     "defaultVideoQuality" TEXT NOT NULL DEFAULT 'auto',
ADD COLUMN     "emailFrom" TEXT,
ADD COLUMN     "emailSupport" TEXT,
ADD COLUMN     "enableInAppNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableMuxStreaming" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableStripeCheckout" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "logLevel" TEXT NOT NULL DEFAULT 'info',
ADD COLUMN     "maxFileSizeMb" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxVideoSizeMb" INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN     "notifyAdminOnPurchase" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyAdminOnRefund" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyStudentOnCertificate" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyStudentOnEnrollment" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "rateLimitMaxRequests" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "rateLimitWindowMs" INTEGER NOT NULL DEFAULT 60000,
ADD COLUMN     "refundPolicyDays" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN     "requireVerifiedEmail" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "sendEnrollmentEmail" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "sendPurchaseConfirmation" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "showTaxBreakdown" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "storagePublicUrl" TEXT,
ADD COLUMN     "stripeCurrency" TEXT NOT NULL DEFAULT 'usd',
ADD COLUMN     "videoSignedPlayback" BOOLEAN NOT NULL DEFAULT true;
