import {
  IconBarbell,
  IconBook,
  IconBrandPython,
  IconBrandYoutube,
  IconBriefcase,
  IconBulb,
  IconCamera,
  IconCategory,
  IconCertificate,
  IconChartBar,
  IconChefHat,
  IconCode,
  IconCoin,
  IconDeviceMobile,
  IconFolders,
  IconHeart,
  IconHome,
  IconLanguage,
  IconLeaf,
  IconMessage,
  IconMusic,
  IconPalette,
  IconPlane,
  IconPresentation,
  IconRobot,
  IconScale,
  IconSchool,
  IconSeo,
  IconShoppingCart,
  IconTarget,
  IconTools,
  IconTrendingUp,
  IconUsers,
  IconWorld,
  IconWriting,
  type TablerIcon,
} from "@tabler/icons-react";

export type CategoryIconName = (typeof CATEGORY_ICON_OPTIONS)[number]["name"];

export const CATEGORY_ICON_OPTIONS = [
  { name: "IconBriefcase", label: "Freelancing" },
  { name: "IconSchool", label: "Educación" },
  { name: "IconCode", label: "Programación" },
  { name: "IconPalette", label: "Diseño" },
  { name: "IconChartBar", label: "Negocios" },
  { name: "IconCoin", label: "Finanzas" },
  { name: "IconLanguage", label: "Idiomas" },
  { name: "IconCamera", label: "Fotografía" },
  { name: "IconMusic", label: "Música" },
  { name: "IconWriting", label: "Escritura" },
  { name: "IconBrandYoutube", label: "Video" },
  { name: "IconSeo", label: "Marketing digital" },
  { name: "IconShoppingCart", label: "E-commerce" },
  { name: "IconHeart", label: "Bienestar" },
  { name: "IconBarbell", label: "Fitness" },
  { name: "IconChefHat", label: "Cocina" },
  { name: "IconHome", label: "Inmobiliaria" },
  { name: "IconDeviceMobile", label: "Apps móviles" },
  { name: "IconBrandPython", label: "Python" },
  { name: "IconRobot", label: "Inteligencia artificial" },
  { name: "IconUsers", label: "Liderazgo" },
  { name: "IconPresentation", label: "Presentaciones" },
  { name: "IconScale", label: "Legal" },
  { name: "IconPlane", label: "Viajes" },
  { name: "IconLeaf", label: "Sostenibilidad" },
  { name: "IconTools", label: "Oficios" },
  { name: "IconCategory", label: "General" },
  { name: "IconFolders", label: "Colecciones" },
  { name: "IconBook", label: "Literatura" },
  { name: "IconCertificate", label: "Certificaciones" },
  { name: "IconTrendingUp", label: "Crecimiento" },
  { name: "IconBulb", label: "Ideas" },
  { name: "IconTarget", label: "Objetivos" },
  { name: "IconMessage", label: "Comunicación" },
  { name: "IconWorld", label: "Web" },
] as const;

export const CATEGORY_ICON_NAMES = CATEGORY_ICON_OPTIONS.map(
  (option) => option.name,
) as [CategoryIconName, ...CategoryIconName[]];

const CATEGORY_ICON_MAP: Record<CategoryIconName, TablerIcon> = {
  IconBriefcase,
  IconSchool,
  IconCode,
  IconPalette,
  IconChartBar,
  IconCoin,
  IconLanguage,
  IconCamera,
  IconMusic,
  IconWriting,
  IconBrandYoutube,
  IconSeo,
  IconShoppingCart,
  IconHeart,
  IconBarbell,
  IconChefHat,
  IconHome,
  IconDeviceMobile,
  IconBrandPython,
  IconRobot,
  IconUsers,
  IconPresentation,
  IconScale,
  IconPlane,
  IconLeaf,
  IconTools,
  IconCategory,
  IconFolders,
  IconBook,
  IconCertificate,
  IconTrendingUp,
  IconBulb,
  IconTarget,
  IconMessage,
  IconWorld,
};

export function resolveCategoryIcon(
  iconName: string | null | undefined,
): TablerIcon | null {
  if (!iconName) return null;
  return CATEGORY_ICON_MAP[iconName as CategoryIconName] ?? null;
}

export function isCategoryIconName(value: string): value is CategoryIconName {
  return value in CATEGORY_ICON_MAP;
}
