import { TooltipProvider } from "@/components/ui/tooltip";
import { clerkProviderAppearance } from "@/lib/clerk/appearance";
import { clerkLocalization } from "@/lib/clerk/localization";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryClientProvider from "@/providers/query-client-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.className} min-h-full flex flex-col font-sans text-base/relaxed text-foreground`}
      >
        <ClerkProvider
          appearance={clerkProviderAppearance}
          localization={clerkLocalization}
        >
          <TooltipProvider>
            <QueryClientProvider>{children}</QueryClientProvider>
          </TooltipProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
