interface AuthIllustrationProps {
  className?: string;
}

export function AuthIllustration({ className }: AuthIllustrationProps) {
  return (
    <svg
      viewBox="0 0 480 360"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden
    >
      <rect
        x="40"
        y="48"
        width="280"
        height="200"
        rx="12"
        fill="currentColor"
        fillOpacity="0.12"
        stroke="currentColor"
        strokeWidth="3"
      />
      <rect
        x="56"
        y="72"
        width="120"
        height="12"
        rx="4"
        fill="currentColor"
        fillOpacity="0.35"
      />
      <rect
        x="56"
        y="96"
        width="200"
        height="8"
        rx="3"
        fill="currentColor"
        fillOpacity="0.2"
      />
      <rect
        x="56"
        y="116"
        width="180"
        height="8"
        rx="3"
        fill="currentColor"
        fillOpacity="0.2"
      />
      <rect
        x="56"
        y="148"
        width="88"
        height="72"
        rx="8"
        fill="currentColor"
        fillOpacity="0.18"
        stroke="currentColor"
        strokeWidth="2"
      />
      <rect
        x="160"
        y="148"
        width="128"
        height="72"
        rx="8"
        fill="currentColor"
        fillOpacity="0.08"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle cx="100" cy="184" r="16" fill="currentColor" fillOpacity="0.35" />
      <path
        d="M200 280 L320 200 L400 240 L400 312 L200 312 Z"
        fill="currentColor"
        fillOpacity="0.15"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinejoin="round"
      />
      <rect
        x="312"
        y="88"
        width="128"
        height="96"
        rx="10"
        fill="var(--background)"
        fillOpacity="0.95"
        stroke="currentColor"
        strokeWidth="3"
      />
      <rect
        x="328"
        y="108"
        width="72"
        height="10"
        rx="3"
        fill="var(--primary)"
      />
      <rect
        x="328"
        y="128"
        width="96"
        height="6"
        rx="2"
        fill="currentColor"
        fillOpacity="0.25"
      />
      <rect
        x="328"
        y="144"
        width="80"
        height="6"
        rx="2"
        fill="currentColor"
        fillOpacity="0.25"
      />
      <rect
        x="328"
        y="164"
        width="56"
        height="8"
        rx="3"
        fill="var(--primary)"
        fillOpacity="0.8"
      />
      <circle
        cx="420"
        cy="72"
        r="28"
        fill="currentColor"
        fillOpacity="0.2"
        stroke="currentColor"
        strokeWidth="2"
      />
      <path
        d="M408 72 L416 80 L432 64"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
